---
- name: Create .jar
  command: chdir=/home/iregueiro/simuladorIoT mvn package

- name: Run main class
  shell: chdir=/home/iregueiro/simuladorIoT java -cp target/xdevs-*.jar xdevs.core.examples.efp.Gpt