---
- name: Delete previous app version
  file:
    state: absent
    path: "{{ clone_dir }}"

- name: Clone a application repository
  git:
    repo: https://github.com/iregue/simuladorIoT.git
    dest: "{{ clone_dir }}"
    version: feature/template
  register: git_download

- name: Debug git 
  debug:
    var: git_download

- name: Get data files
  command: gsutil -m cp -r gs://simulador-iot-tfm-irt/{{ item }} {{ dest }}
  loop: "{{ ficheros }}"