template_path: ~/simuladorIoT/src/xdevs/core/examples/efp
gpt_path: ~/simuladorIoT/src/xdevs/core/examples/efp/Gpt.java
fog_server_path: ~/simuladorIoT/src/xdevs/core/examples/efp/FogServer.java
data_center_path: ~/simuladorIoT/src/xdevs/core/examples/efp/DataCenter.java
ficheros:
  - ap1
  - ap5
nodo_virtual:
  - nodoVirtual1
  - nodoVirtual2
fog_server:
  - name: fogserver1
    krigingX: 70.0
    krigingY: 75.0
    coordenadasNodosX: 1.0, 2.0, 3.0
    coordenadasNodosY: 4.0, 3.0, 5.0
data_center:
  - dataCenter
conectores:
  - out_type: ficheros
    out: ap1
    in: nodoVirtual1
  - out_type: ficheros
    out: ap5
    in: nodoVirtual2
  - out_type: nodoVirtual
    out: nodoVirtual1
    in: fogserver1
  - out_type: nodoVirtual
    out: nodoVirtual2
    in: fogserver1
  - out_type: fogServer
    out: fogserver1
    in: dataCenter
deltext:
  - nodoVirtual1
  - nodoVirtual2
